import {
  HERO_KIND_ORDER,
  HERO_PINS,
  HERO_YOU_ARE_HERE,
  matchesFilter,
  nearestPin,
  type HeroFilter,
} from "@/lib/marketing/hero-map";
import { HERO_ROUTE_MAX_POINTS } from "@/lib/marketing/hero-routes";
import { getRouter } from "@/lib/routing";
import { simplifyPath } from "@/lib/routing/simplify";
import type { LngLatTuple } from "@/packages/shared/shapes";

/**
 * Development only: the source of `lib/marketing/hero-routes.ts`.
 *
 * The hero's "Nearest to me" draws a real road route, and CLAUDE.md §2 forbids
 * the landing page asking a routing engine for it — so the geometry is baked
 * and committed, exactly as the basemap under it is. This is where it comes
 * from: one request per destination, in development, against whatever
 * `ROUTING_PROVIDER` is configured, returning the finished module as text.
 *
 * `/dev/hero-map` has a button that downloads it; `curl` works just as well.
 * It 404s in a production build, the same gate that page uses.
 *
 * **The destinations are derived, never listed.** Whatever `nearestPin` can
 * answer for each of the filter chips is what gets a route, so editing
 * `HERO_PINS` and regenerating stays correct with no second list to update.
 */
export async function GET() {
  if (process.env.NODE_ENV === "production") {
    return new Response(null, { status: 404 });
  }

  const filters: HeroFilter[] = ["all", ...HERO_KIND_ORDER];
  const targets = new Map<string, LngLatTuple>();

  for (const filter of filters) {
    const shown = HERO_PINS.filter((pin) => matchesFilter(pin, filter));
    const nearest = nearestPin(HERO_YOU_ARE_HERE, shown)?.pin;

    if (nearest) targets.set(nearest.name, [nearest.lng, nearest.lat]);
  }

  const from: LngLatTuple = [HERO_YOU_ARE_HERE.lng, HERO_YOU_ARE_HERE.lat];
  const router = getRouter();
  const entries: string[] = [];

  try {
    for (const [name, to] of targets) {
      const { route } = await router.route({ stops: [from, to], profile: "car" });

      if (!route) {
        return text(`No route to ${name} — the engine answered, and found none.`, 502);
      }

      entries.push(entry(name, route.points, route.distanceM, route.durationS));
    }
  } catch (caught) {
    return text(caught instanceof Error ? caught.message : String(caught), 502);
  }

  return text(module(entries, router.name));
}

/** Five decimals is about a metre, which is finer than a 1,440px-wide picture can draw. */
function round(value: number): number {
  return Math.round(value * 1e5) / 1e5;
}

function entry(
  name: string,
  points: readonly LngLatTuple[],
  distanceM: number,
  durationS: number,
): string {
  const thinned = simplifyPath(points, HERO_ROUTE_MAX_POINTS)
    .map(([lng, lat]) => `      [${round(lng)}, ${round(lat)}],`)
    .join("\n");

  return `  ${JSON.stringify(name)}: {
    to: ${JSON.stringify(name)},
    distanceM: ${Math.round(distanceM)},
    durationS: ${Math.round(durationS)},
    points: [
${thinned}
    ],
  },`;
}

function module(entries: string[], engine: string): string {
  return `import type { HeroRoute } from "./hero-routes";

/**
 * Generated by \`/dev/hero-routes\` on ${new Date().toISOString().slice(0, 10)}.
 *
 * Do not edit by hand — see lib/marketing/hero-routes.ts for what this is and
 * how to make it again.
 */

/** Which engine measured these, so the hero can credit it. */
export const HERO_ROUTE_ENGINE = ${JSON.stringify(engine)};

export const HERO_ROUTE_DATA: Record<string, HeroRoute> = {
${entries.join("\n")}
};
`;
}

function text(body: string, status = 200): Response {
  return new Response(body, {
    status,
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
}
