import type { ImportField } from "../fields";

/**
 * Header spellings we recognise, normalised (see normalize.ts — accents are
 * already folded, so "telefono" covers "Teléfono").
 *
 * Ordered most to least specific within a field, because a more specific synonym
 * outranks a vaguer one at the same match tier.
 *
 * Non-English entries are here because the customers are: CLAUDE.md prices this
 * in €, and a German dealer list says "Straße" and "PLZ", not "Street" and
 * "Postcode". Covering the six languages a European brand is most likely to
 * export in costs a table and buys a mapping step that starts out correct
 * instead of empty. Values still decide when headers disagree — see
 * value-signals.ts — this only has to get the common case right.
 */
export const FIELD_SYNONYMS: Record<ImportField, readonly string[]> = {
  name: [
    "name",
    "locationname",
    "storename",
    "shopname",
    "businessname",
    "companyname",
    "dealername",
    "stockist",
    "venue",
    "location",
    "store",
    "shop",
    "business",
    "company",
    "dealer",
    "title",
    "label",
    // de / fr / es / it / nl / pl
    "bezeichnung",
    "filiale",
    "haendler",
    "geschaeft",
    "standort",
    "nom",
    "magasin",
    "enseigne",
    "nombre",
    "tienda",
    "negozio",
    "naam",
    "winkel",
    "nazwa",
    "sklep",
  ],
  address: [
    "streetaddress",
    "addressline1",
    "address1",
    "addressline",
    "fulladdress",
    "address",
    "street",
    "addr",
    "road",
    // de / fr / es / it / nl / pl
    "strasse",
    "anschrift",
    "adresse",
    "hausnummer",
    "rue",
    "voie",
    "direccion",
    "calle",
    "indirizzo",
    "via",
    "adres",
    "straat",
    "ulica",
  ],
  city: [
    "city",
    "town",
    "locality",
    "suburb",
    "posttown",
    // de / fr / es / it / nl / pl
    "stadt",
    "ort",
    "wohnort",
    "ville",
    "commune",
    "ciudad",
    "poblacion",
    "citta",
    "comune",
    "plaats",
    "gemeente",
    "miasto",
    "miejscowosc",
  ],
  postcode: [
    "postcode",
    "postalcode",
    "zipcode",
    "zip",
    "plz",
    "cp",
    // de / fr / es / it / nl / pl
    "postleitzahl",
    "codepostal",
    "codigopostal",
    "cap",
    "postcodenl",
    "kodpocztowy",
  ],
  state: [
    "state",
    "province",
    "region",
    "county",
    "district",
    // de / fr / es / it / nl / pl
    "bundesland",
    "kanton",
    "departement",
    "provincia",
    "comunidad",
    "regione",
    "provincie",
    "wojewodztwo",
  ],
  country: [
    "country",
    "countrycode",
    "nation",
    // de / fr / es / it / nl / pl
    "land",
    "pays",
    "pais",
    "paese",
    "kraj",
  ],
  category: [
    "category",
    "type",
    "kind",
    "group",
    "segment",
    "tag",
    "classification",
    // de / fr / es / it / nl / pl
    "kategorie",
    "typ",
    "gruppe",
    "categorie",
    "categoria",
    "tipo",
    "kategoria",
    "rodzaj",
  ],
  description: [
    "description",
    "about",
    "notes",
    "details",
    "summary",
    "info",
    // de / fr / es / it / nl / pl
    "beschreibung",
    "hinweise",
    "descriptif",
    "descripcion",
    "descrizione",
    "omschrijving",
    "opis",
  ],
  phone: [
    "phone",
    "phonenumber",
    "telephone",
    "tel",
    "mobile",
    "contactnumber",
    // de / fr / es / it / nl / pl
    "telefon",
    "telefonnummer",
    "rufnummer",
    "portable",
    "telefono",
    "movil",
    "telefoon",
    "numertelefonu",
  ],
  email: [
    "email",
    "emailaddress",
    "mail",
    "contactemail",
    // de / fr / es / it / nl / pl
    "epost",
    "courriel",
    "correo",
    "posta",
    "epostadres",
  ],
  url: [
    "url",
    "website",
    "web",
    "homepage",
    "link",
    "site",
    "webaddress",
    // de / fr / es / it / nl / pl
    "webseite",
    "internet",
    "sitioweb",
    "sitoweb",
    "strona",
  ],
  lat: [
    "latitude",
    "lat",
    "ycoordinate",
    "y",
    // de / fr / es / it / nl / pl
    "breitengrad",
    "szerokosc",
    "latitud",
    "latitudine",
    "breedtegraad",
  ],
  lng: [
    "longitude",
    "lng",
    "long",
    "lon",
    "xcoordinate",
    "x",
    // de / fr / es / it / nl / pl
    "laengengrad",
    "dlugosc",
    "longitud",
    "longitudine",
    "lengtegraad",
  ],
  latlng: [
    "latlng",
    "latlong",
    "latitudelongitude",
    "coordinates",
    "coordinate",
    "coords",
    "geo",
    "geolocation",
    "position",
    "point",
    "maplink",
    "googlemaps",
    // de / fr / es / it / nl / pl
    "koordinaten",
    "coordonnees",
    "coordenadas",
    "wspolrzedne",
  ],
};
