<?php
/**
 * Which Pinglide map each dropped map shows.
 *
 * A block (or shortcode) carries a random `slot` id, never a map id: the answer
 * to "which map?" arrives later, in wp-admin, after the owner has been to
 * pinglide.com and back — somewhere that cannot write into the post's content.
 * So the answer is kept here, one option for the whole site:
 *
 *   slot => { map, name, snapshot, script, connected_at, connected_by }
 *
 * Two blocks are two slots and so two maps; they cannot be confused. A copied
 * block keeps its slot and shows the same map, which is what copying means.
 *
 * Nothing in it is secret. `snapshot` is the map's public, stable URL — the same
 * one a pasted embed snippet carries.
 *
 * @package Pinglide
 */

defined( 'ABSPATH' ) || exit;

final class Pinglide_Slots {

	const OPTION = 'pinglide_slots';

	/**
	 * The shape every slot id has. Generated by the block (crypto.randomUUID) or
	 * by the settings page (wp_generate_uuid4), and checked on every way in.
	 *
	 * @param mixed $slot Candidate id.
	 */
	public static function is_valid_id( $slot ): bool {
		return is_string( $slot ) && 1 === preg_match( '/^[A-Za-z0-9-]{8,64}$/', $slot );
	}

	/**
	 * @param string $slot Slot id.
	 * @return array|null The connected map, or null when this slot has none yet.
	 */
	public static function get( $slot ) {
		if ( ! self::is_valid_id( $slot ) ) {
			return null;
		}

		$all = self::all();

		return isset( $all[ $slot ] ) ? $all[ $slot ] : null;
	}

	/**
	 * @return array<string, array> Every connection on this site.
	 */
	public static function all(): array {
		$all = get_option( self::OPTION, array() );

		return is_array( $all ) ? $all : array();
	}

	/**
	 * @param string $slot Slot id.
	 * @param array  $map  { map, name, snapshot, script }.
	 */
	public static function set( $slot, array $map ): void {
		if ( ! self::is_valid_id( $slot ) ) {
			return;
		}

		$all          = self::all();
		$all[ $slot ] = array(
			'map'          => (string) $map['map'],
			'name'         => (string) $map['name'],
			'snapshot'     => (string) $map['snapshot'],
			'script'       => (string) $map['script'],
			'connected_at' => time(),
			'connected_by' => get_current_user_id(),
		);

		// Autoloaded: every page with a map on it reads this, and it is small.
		update_option( self::OPTION, $all );
	}

	/**
	 * @param string $slot Slot id.
	 */
	public static function remove( $slot ): void {
		$all = self::all();

		if ( isset( $all[ $slot ] ) ) {
			unset( $all[ $slot ] );
			update_option( self::OPTION, $all );
		}
	}

	/**
	 * Where the owner manages a connected map's locations.
	 *
	 * @param array $map A stored connection.
	 */
	public static function edit_url( array $map ): string {
		return untrailingslashit( PINGLIDE_APP_URL ) . '/maps/' . rawurlencode( $map['map'] );
	}
}
